### ISSUE TITLE
Generator having issues when trying to randomize (0.8.1, exe version, vanilla SM64)

### ISSUE THREAD

**Issue by yourizuring** [andrelikesdogs/sm64-randomizer#17]
![image](https://user-images.githubusercontent.com/47860706/75477126-1dec0a00-599c-11ea-918f-682c0f4c662c.png)

Basically it's having issues with Bowser In The Fire Sea and Bowser In The Dark World.
This issue is also posted on Discord.

**Comment by andrelikesdogs** [comment]
Thank you for your report!
The messages you're seeing were debugging messages, indicating an invalid shuffle, for example because "Bowser in the Fire Sea" required the upstairs keys to be reached, but also awarded the upstairs key. In this case the shuffle is discarded and it tries again until it finds one without an invalid route, which is the intended functionality. I'll make sure the messages are less confusing or just disable them as they were pretty much just debugging help.
