### ISSUE TITLE
Random Painting feature still not fixed

### ISSUE THREAD

**Issue by Irgendwer01** [andrelikesdogs/sm64-randomizer#38]
Comment 1607ca6 doesn't fixes the issue.

**Comment by andrelikesdogs** [comment]
Hey there, thank you for your interest in the randomizer. This fix has been implemented a while ago but I haven't made a new release as I suddenly became very busy with life. I have since created an automatic release pipeline that's almost finished. For now, you can use these nightly builds which have the bug fixed.
