### ISSUE TITLE
generation fail

### ISSUE THREAD

**Issue by Alfredo1802** [andrelikesdogs/sm64-randomizer#59]
everytime i try to generate a new rom it says this:

The generator timed out, it took to long to generate this ROM. There is probably a problem with this ROM. Please report this error using this upload-id: b90946ea-0ee7-4c14-885d-22ebb23913f7

**Comment by Openstreetmapler** [comment]
Same issue over here. 😢 And no fix yet.

Unfortunately, I can’t get that macOS download application to work either (see Python error in Terminal below):

> [28222] Error loading Python lib '/var/folders/fr/wpjvh4q93nz_kjn6x9352ydh0000gp/T/_MEIDGwmo3/Python': dlopen: dlopen(/var/folders/fr/wpjvh4q93nz_kjn6x9352ydh0000gp/T/_MEIDGwmo3/Python, 10): Symbol not found: _futimens
>   Referenced from: /var/folders/fr/wpjvh4q93nz_kjn6x9352ydh0000gp/T/_MEIDGwmo3/Python
>   Expected in: /usr/lib/libSystem.B.dylib
>  in /var/folders/fr/wpjvh4q93nz_kjn6x9352ydh0000gp/T/_MEIDGwmo3/Python
> logout
> Saving session...
> ...copying shared history...
> ...saving history...truncating history files...
> ...completed.

**Comment by Openstreetmapler** [comment]
**Please fix it! I am so sad right now that I can’t play randomized Super Mario 64!**

**Comment by andrelikesdogs** [comment]
Hey there! Thank you for your interest in the randomizer and apologies for my late response, I've been very busy recently and haven't gotten around to addressing many pull-requests.
The issue you see on the web-generator is because the server I host this project on is running the randomizer with very limited resources as I haven't been able to upgrade it to a bigger machine. You'll need to run the applocation on your device - I recommend these nightly builds, they have the most recent bugs fixes:
https://github.com/andrelikesdogs/sm64-randomizer/actions/runs/717465821
