### ISSUE TITLE
Rom Hack Incompatibility 

### ISSUE THREAD

**Issue by chrisbrutalagresion** [andrelikesdogs/sm64-randomizer#77]
i found an error trying to randomize my project, b3313 (https://www.youtube.com/watch?v=XchBFIon_P4&ab_channel=ChristopherRiosLillo) it's a really big hack and i really wanted to use randomizer on this, but neither the page or the program works on this

**Comment by andrelikesdogs** [comment]
Thank you for trying out the randomizer! I'm afraid this won't quite work, as this is a remake of the Beta version, which has too many code differences. I will investigate further but I'm suspect some underlying functionality used in this romhack (how levels are loaded, how "behaviours" work, how level geometry works) isn't compatible with what my randomizer expects. Sorry :(

**Comment by andrelikesdogs** [comment]
Sorry for getting back to you so late. I'm having issues working on getting romhacks to work with the generator unfortunately. I've since removed the claims from the description that it's possible. It *is* technically possible, but a lot of knowledge is required to adjust the randomizer to make it work and it's only gotten more difficult the more updates I make to it.

If you have any experience with romhacking and would like to help out, I'm available to advise and help out with figuring out how to do this for an individiual hack via Discord: andre#1096
