### ISSUE TITLE
Doesnt work with Decomp-Hack

### ISSUE THREAD

**Issue by BBO467** [andrelikesdogs/sm64-randomizer#79]
I made a "Romhack", that is just changing some 3D-Models and colors, but nothing with the games code but when i try to apply the rando, it doesnt work. I also already extended it. It says "index out of range"

Here is the log:

https://pastebin.com/cvw7fZdH

Please help me!

**Comment by andrelikesdogs** [comment]
Sorry for getting back to you so late. I'm having issues working on getting romhacks to work with the generator unfortunately. I've since removed the claims from the description that it's possible. It *is* technically possible, but a lot of knowledge is required to adjust the randomizer to make it work and it's only gotten more difficult the more updates I make to it.

If you have any experience with romhacking and would like to help out, I'm available to advise and help out with figuring out how to do this for an individiual hack via Discord: andre#1096
